name: 'Update one grade'
description: 'Update grade in spreadsheet from merged pull-request'
inputs:
  github-token:
    description: 'Github token'
    required: true
    default: "${{ github.token }}"
  number-of-pr:
    description: 'Number of pull request'
    required: true
    default: '1'
  repository-name:
    description: 'Full name of repo. Format.: <owner>/<name of repo>'
    required: true
    default: ${{ github.event.repository.full_name }}
  update-google-table:
    description: 'Whether or not to update grades in google table'
    required: true
    default: false

branding:
  icon: 'book'
  color: 'gray-dark'

runs:
  using: 'composite'
  steps:
      - run: |
          PAYLOAD='{
            "command": "update_grade_with_merged_pull_requests",
            "arguments": {
              "repository_name": "${{ inputs.repository-name }}",
              "github_token": "${{ inputs.github-token }}",
              "number_of_pr": "${{ inputs.number-of-pr }}"
            }
          }'
          curl -X 'POST' \
            "$SERVER_URL/run_command/" \
            -H 'accept: application/json' \
            -H 'Content-Type: application/json' \
            -d "$PAYLOAD"
        shell: bash
