# action.yml
name: 'Commits in main'
description: 'Looking for commits in protected branches'
inputs:
  github-token:  
    description: 'Github token'
    required: true
    default: "${{ github.token }}"
  repository-name:
    description: 'Full name of repo. Format.: <owner>/<name of repo>'
    required: true
    default: ${{ github.event.repository.full_name }}

branding:
  icon: 'book'  
  color: 'gray-dark'

runs:
  using: 'composite'
  steps:
    - run: docker run --pull=always --rm --network=host -v ${PR_BOT_CONFIG_PATH}:/config -v ${VOLUME_NAME}:/repository_files mirrin/moevm-pull-requests-checker:v2.0.0 check_main_commits -github_token ${{ inputs.github-token }} -repository_name ${{ inputs.repository-name }} -output_file main_commits.json
      shell: bash

    - name: Save reports
      uses: actions/upload-artifact@v3
      with:
        name: reports
        path: ./main_commits.json
        retention-days: 3
        if-no-files-found: error
